
#define CONSOLE_MAX_CMDLINE_ARGS 8
#define CONSOLE_MAX_CMDLINE_LENGTH 256
#define CONSOLE_PROMPT_MAX_LEN (32)

#define CONFIG_CONSOLE_STORE_HISTORY 0
#define CONFIG_CONSOLE_IGNORE_EMPTY_LINES 1
#define PROMPT_STR CONFIG_IDF_TARGET

#define MOUNT_PATH "/sdcard"
#define HISTORY_PATH MOUNT_PATH "/history.txt"

#define CONSOLE_PROMPT_MAX_LEN (32)